apiVersion: v1
kind: Pod
metadata:
  name: amvitech-frontend
  labels:
    name: amvitech-frontend
    type: front-end
spec:
  containers:
  - name: amvitech-frontend
    image: vijayw19/amvitech-frontend:latest