apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: amvitech-frontend-rc
  labels:
    name: react-app-rc
    type: frontend
spec:
  template:
    metadata:
      name: amvitech-frontend
      labels:
        name: amvitech-frontend
        type: front-end
    spec:
      containers:
      - name: amvitech-frontend
        image: vijayw19/amvitech-frontend:latest
  replicas: 4
  selector:
     matchLabels:
        name: amvitech-frontend



