apiVersion: v1
kind: Service
metadata:
  name:  amvitech-backend-service
spec:
  selector:
    name: amvitech-backend
  type: NodePort
  ports:
  - port:  8087
    targetPort:  8080
    nodePort: 30007