apiVersion: v1
kind: Service
metadata:
  name:  amvitech-frontend-service
spec:
  selector:
    name:  amvitech-frontend
  type: NodePort
  ports:
  - port: 3000
    targetPort:  3000
    nodePort: 31001